# Generated by Django 5.2.8 on 2025-11-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "Лайк", "verbose_name_plural": "Лайки"},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео"},
        ),
        migrations.AlterModelOptions(
            name="videofile",
            options={"verbose_name": "Видеофайл", "verbose_name_plural": "Видеофайлы"},
        ),
        migrations.AlterField(
            model_name="videofile",
            name="quality",
            field=models.CharField(
                choices=[("1", "HD"), ("2", "FHD"), ("3", "UHD")], max_length=1
            ),
        ),
    ]
