# Generated by Django 5.2.8 on 2025-11-17 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_like_options_alter_video_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="file",
            field=models.FileField(blank=True, upload_to="videos", verbose_name="Файл"),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("video", "user"), name="unique_like"
            ),
        ),
    ]
